### ISSUE TITLE
Type specifier Error

### ISSUE THREAD

**Issue by SV-Krishna** [Boatingwiththebaileys/ESP32-code#1]
Hello

I had previously implemented this code, had it all working. I needed to build again so copied and pasted the main.cpp and platformio.ini file but I get a compile error

src/main.cpp:119:26: error: expected type-specifier before 'Frequency'
   sensor->connect_to(new Frequency(multiplier, config_path_calibrate))

Any clues?

**Comment by Boatingwiththebaileys** [comment]
Thanks for highlighting this, it was missing this line from the top, which calls frequency.h

#include "sensesp/transforms/frequency.h"

**Comment by SV-Krishna** [comment]
Awesome, will give that a go and BTW huge thanks for the inspiration to do all of this, learning so much
